### ISSUE TITLE
About the version of jim and flowMC

### ISSUE THREAD

**Issue by yanyuechuixue** [ThibeauWouters/TurboPE-BNS#1] opened 2024-04-12 08:05 UTC
Dear Colleagues, 

Thanks for developing these  excellent tools.
I want to reproduce your work and then use this tool to do a injection simulation.
However, I don't know the exact version this tool depends on.
If possible, could you tell us which version of jim and flowMC we should use?

Thanks a lot.

**Comment by ThibeauWouters** [comment] 2024-04-12 09:25
Hi,

Thanks a lot for the interest in our work! Indeed, since we are still writing the paper, we have not yet updated the README of the repo to tell people how to easily reproduce the work shown here. However, you can try the following:

1. Get the versions from my forks of flowMC, jim and ripple. I will link the repos below and mention the names branches I am currently using for this research.

- [ripple fork](https://github.com/ThibeauWouters/ripple), branch `no_taper`
- [flowMC fork](https://github.com/ThibeauWouters/flowMC), branch `main`
- [jim fork](https://github.com/ThibeauWouters/jim), branch `TaylorF2QM`

2. Alternatively, if you have access to the [LDAS CIT cluster](https://computing.docs.ligo.org/guide/computing-centres/cit/), you can activate the conda environment that I used to perform these runs:
`/home/thibeau.wouters/miniconda3/envs/jim`
and run the injections that are in this repository with that conda environment activated

Let me know if this is sufficient for you to get started already. Note that both flowMC and jim are going under activate maintenance right now, such that our version will be outdated by the time the paper will actually be released publicly.

**Comment by ThibeauWouters** [comment] 2024-04-12 09:40
Hi,

Unfortunately, we are still writing the paper and will share more information regarding how to reproduce the results in details after the paper has appeared on arXiv. We will get back to you ASAP on this matter.

**Comment by ThibeauWouters** [comment] 2024-04-18 11:51
Hi @yanyuechuixue ,

We have just released the paper on arXiv today! You can find it [here](https://arxiv.org/abs/2404.11397). I have also accordingly updated the `README.md` to answer your question as well as created a Zenodo release that you can find in the `README.md` with all necessary details regarding the software used. 

I believe this is sufficient information to close this issue. If you run into problems, feel free to contact me or raise another issue.

**Closed as completed by ThibeauWouters** 2024-04-18 11:51 UTC

**Comment by yanyuechuixue** [comment] 2024-04-18 13:19
Thank you very much!
